name: Build and Push to Docker Hub

on:
  push:
    branches: [ master ]  # You can keep using 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Updated to v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5  # Updated to v5 (latest stable)
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/eventmanagementsystem:latest
